### ISSUE TITLE
Method to reset to initial state.

### ISSUE THREAD

**Issue by AnghelGabriel** [Cinamonas/jquery-drilldown#1]
Hi,
I added this plugin to a hover / drop down menu. I want a tip on how i could reset it to initial state when the menu is hoverOut.

Can you help me with this.
Regrads.

**Comment by Cinamonas** [comment]
I do realize you guys solved it yourselves long ago, but I can finally close this issue as I was able to get some coding done for this project and the just released v1.0.0 implements `reset` method.
