### ISSUE TITLE
Bootstrap 3 Compatibility

### ISSUE THREAD

**Issue by bogacg** [Cinamonas/jquery-drilldown#3]
Hi,
I was trying to implement jquery drilldown to an existing Bootstrap 3 navbar. When I do, navbar sub-menu items goes behind an image element I have just below navbar (see image). I've tried to add z-index to .drilldown in css, but no luck.

Did you use it with Bootstrap 3?

Thanks

![bootstrap3_jquerydrilldown](https://cloud.githubusercontent.com/assets/5073927/4790082/e41480da-5dcc-11e4-9460-ddbfad9190de.jpg)

**Comment by mewsoft** [comment]
Yes I also recommend porting this to Bootstrap, would be nice addition.

**Comment by Cinamonas** [comment]
Sorry for late reply.

The plugin allows to customize the CSS classes it uses through `cssClass` option. And such `zIndex` should be addressable from outside without implementing a direct "compatibility with Bootstrap".
