### ISSUE TITLE
Drilldown does not maintain state of input DOM elements

### ISSUE THREAD

**Issue by marlongichie** [Cinamonas/jquery-drilldown#4]
In my drilldown menu, I have elements which are input elements. I have noticed that the drilldown menu does not keep the values of these input elements when the menu is updated.

I suspect this is because the actual elements are not injected into the drilldown-root element, but instead a clone.

Would be nice to have support for this use case.

I suggest, using some sort of class attribute to identify the trigger which was clicked, then instead of injecting a `$.clone` version of the DOM, to use the actual DOM element `($next)`, and finally when the drilldown goes back up, restore the original `.drilldown-sub` class and finally use `$.insertAfter`  to place the actual DOM elements back to the original position.

Any thoughts?

**Comment by jamescazzetta** [comment]
I have encountered the same "issue", would be very nice to have a support for this.

**Comment by oterral** [comment]
@marlongichie  I think I have the same problem using this drilldown and angular-gettext. I come with a PR to fix this.

**Comment by Cinamonas** [comment]
This has been implemented by @oterral in #7 and landed into the codebase.
