### ISSUE TITLE
_history isn't accurate with the current state of shown list

### ISSUE THREAD

**Issue by jamescazzetta** [Cinamonas/jquery-drilldown#5]
This might not directly be an issue, but would definitely be an awesome functionality enhancement in my opinion. I am failing because the "_history" value always is one click in delay, so I need to trigger the click 1 more time anywhere in the drilldown container to have the "_history" data updated. Is this intended? Or differently asked, could the "_history" part be modified in a way, so that one could use it as iterable data for breadcrumbs?

This is what I have so far.
$('div.drilldown').drilldown().on('click.drilldown', function(){
    // Empty breadcrumb list
    $('#drill-crumbs').empty();
    $.each($drillSelector.data('drilldown')._history, function(index, value){
        $drillCrumbs.append('> <a href="javascript:void(0)">' + value.context.firstChild.data + '</a>');
    }).on('mouseenter', function(){
        // This will re trigger and make the history update.. (example, shouldn't be done this way)
        $(this).trigger('click');
    });
})

Do you know what I mean or am I doing something thats "not intended"? ;-)
Anyway, very nice plugin!! cheers

**Comment by Cinamonas** [comment]
Sorry for late reply.

History is updated after drilling animation finishes. That's where the delay you've described is coming from. And `_history` is not intended for direct access as it's marked as private. This could be improved, but is out of scope right now.
